// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for `src/vad_plus.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class VadPlusBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VadPlusBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VadPlusBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Create default VAD configuration for Silero VAD
  /// @param config_out Pointer to VADConfig struct to fill with default values
  void vad_config_default(ffi.Pointer<VADConfig> config_out) {
    return _vad_config_default(config_out);
  }

  late final _vad_config_defaultPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VADConfig>)>>(
        'vad_config_default',
      );
  late final _vad_config_default = _vad_config_defaultPtr
      .asFunction<void Function(ffi.Pointer<VADConfig>)>();

  /// Create a new VAD instance
  /// @return Pointer to new VAD handle, or NULL on failure
  ffi.Pointer<VADHandle> vad_create() {
    return _vad_create();
  }

  late final _vad_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<VADHandle> Function()>>(
        'vad_create',
      );
  late final _vad_create = _vad_createPtr
      .asFunction<ffi.Pointer<VADHandle> Function()>();

  /// Destroy a VAD instance and free resources
  /// @param handle VAD handle to destroy
  void vad_destroy(ffi.Pointer<VADHandle> handle) {
    return _vad_destroy(handle);
  }

  late final _vad_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VADHandle>)>>(
        'vad_destroy',
      );
  late final _vad_destroy = _vad_destroyPtr
      .asFunction<void Function(ffi.Pointer<VADHandle>)>();

  /// Initialize VAD with configuration and model
  /// @param handle VAD handle
  /// @param config Pointer to VAD configuration
  /// @param model_path Path to ONNX model file (can be NULL for bundled model)
  /// @return 0 on success, negative error code on failure
  int vad_init(
    ffi.Pointer<VADHandle> handle,
    ffi.Pointer<VADConfig> config,
    ffi.Pointer<ffi.Char> model_path,
  ) {
    return _vad_init(handle, config, model_path);
  }

  late final _vad_initPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VADHandle>,
            ffi.Pointer<VADConfig>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('vad_init');
  late final _vad_init = _vad_initPtr
      .asFunction<
        int Function(
          ffi.Pointer<VADHandle>,
          ffi.Pointer<VADConfig>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Set the event callback for VAD events
  /// @param handle VAD handle
  /// @param callback Event callback function
  /// @param user_data User data passed to callback
  void vad_set_callback(
    ffi.Pointer<VADHandle> handle,
    VADEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _vad_set_callback(handle, callback, user_data);
  }

  late final _vad_set_callbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<VADHandle>,
            VADEventCallback,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('vad_set_callback');
  late final _vad_set_callback = _vad_set_callbackPtr
      .asFunction<
        void Function(
          ffi.Pointer<VADHandle>,
          VADEventCallback,
          ffi.Pointer<ffi.Void>,
        )
      >();

  /// Invalidate the callback to prevent it from being invoked
  /// This MUST be called before closing the Dart NativeCallable to prevent crashes.
  /// Uses synchronous dispatch to ensure all pending callbacks complete first.
  /// @param handle VAD handle
  void vad_invalidate_callback(ffi.Pointer<VADHandle> handle) {
    return _vad_invalidate_callback(handle);
  }

  late final _vad_invalidate_callbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VADHandle>)>>(
        'vad_invalidate_callback',
      );
  late final _vad_invalidate_callback = _vad_invalidate_callbackPtr
      .asFunction<void Function(ffi.Pointer<VADHandle>)>();

  /// Start audio capture and VAD processing
  /// @param handle VAD handle
  /// @return 0 on success, negative error code on failure
  int vad_start(ffi.Pointer<VADHandle> handle) {
    return _vad_start(handle);
  }

  late final _vad_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VADHandle>)>>(
        'vad_start',
      );
  late final _vad_start = _vad_startPtr
      .asFunction<int Function(ffi.Pointer<VADHandle>)>();

  /// Stop audio capture and VAD processing
  /// @param handle VAD handle
  void vad_stop(ffi.Pointer<VADHandle> handle) {
    return _vad_stop(handle);
  }

  late final _vad_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VADHandle>)>>(
        'vad_stop',
      );
  late final _vad_stop = _vad_stopPtr
      .asFunction<void Function(ffi.Pointer<VADHandle>)>();

  /// Process audio samples directly (without microphone capture)
  /// Use this when you have your own audio source
  /// @param handle VAD handle
  /// @param samples Pointer to float32 audio samples (normalized -1.0 to 1.0)
  /// @param sample_count Number of samples
  /// @return 0 on success, negative error code on failure
  int vad_process_audio(
    ffi.Pointer<VADHandle> handle,
    ffi.Pointer<ffi.Float> samples,
    int sample_count,
  ) {
    return _vad_process_audio(handle, samples, sample_count);
  }

  late final _vad_process_audioPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VADHandle>,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
          )
        >
      >('vad_process_audio');
  late final _vad_process_audio = _vad_process_audioPtr
      .asFunction<
        int Function(ffi.Pointer<VADHandle>, ffi.Pointer<ffi.Float>, int)
      >();

  /// Reset VAD state (clear buffers and speech detection state)
  /// @param handle VAD handle
  void vad_reset(ffi.Pointer<VADHandle> handle) {
    return _vad_reset(handle);
  }

  late final _vad_resetPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VADHandle>)>>(
        'vad_reset',
      );
  late final _vad_reset = _vad_resetPtr
      .asFunction<void Function(ffi.Pointer<VADHandle>)>();

  /// Force end current speech segment if any
  /// @param handle VAD handle
  void vad_force_end_speech(ffi.Pointer<VADHandle> handle) {
    return _vad_force_end_speech(handle);
  }

  late final _vad_force_end_speechPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VADHandle>)>>(
        'vad_force_end_speech',
      );
  late final _vad_force_end_speech = _vad_force_end_speechPtr
      .asFunction<void Function(ffi.Pointer<VADHandle>)>();

  /// Check if VAD is currently detecting speech
  /// @param handle VAD handle
  /// @return 1 if speech is being detected, 0 otherwise
  int vad_is_speaking(ffi.Pointer<VADHandle> handle) {
    return _vad_is_speaking(handle);
  }

  late final _vad_is_speakingPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<VADHandle>)>>(
        'vad_is_speaking',
      );
  late final _vad_is_speaking = _vad_is_speakingPtr
      .asFunction<int Function(ffi.Pointer<VADHandle>)>();

  /// Get the last error message
  /// @param handle VAD handle
  /// @return Error message string (do not free)
  ffi.Pointer<ffi.Char> vad_get_last_error(ffi.Pointer<VADHandle> handle) {
    return _vad_get_last_error(handle);
  }

  late final _vad_get_last_errorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<VADHandle>)
        >
      >('vad_get_last_error');
  late final _vad_get_last_error = _vad_get_last_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<VADHandle>)>();

  /// Convert float32 audio samples to PCM16
  /// @param float_samples Input float32 samples (-1.0 to 1.0)
  /// @param pcm16_samples Output PCM16 buffer (must be allocated)
  /// @param sample_count Number of samples
  void vad_float_to_pcm16(
    ffi.Pointer<ffi.Float> float_samples,
    ffi.Pointer<ffi.Int16> pcm16_samples,
    int sample_count,
  ) {
    return _vad_float_to_pcm16(float_samples, pcm16_samples, sample_count);
  }

  late final _vad_float_to_pcm16Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Float>,
            ffi.Pointer<ffi.Int16>,
            ffi.Int32,
          )
        >
      >('vad_float_to_pcm16');
  late final _vad_float_to_pcm16 = _vad_float_to_pcm16Ptr
      .asFunction<
        void Function(ffi.Pointer<ffi.Float>, ffi.Pointer<ffi.Int16>, int)
      >();

  /// Convert PCM16 audio samples to float32
  /// @param pcm16_samples Input PCM16 samples
  /// @param float_samples Output float32 buffer (must be allocated)
  /// @param sample_count Number of samples
  void vad_pcm16_to_float(
    ffi.Pointer<ffi.Int16> pcm16_samples,
    ffi.Pointer<ffi.Float> float_samples,
    int sample_count,
  ) {
    return _vad_pcm16_to_float(pcm16_samples, float_samples, sample_count);
  }

  late final _vad_pcm16_to_floatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Int16>,
            ffi.Pointer<ffi.Float>,
            ffi.Int32,
          )
        >
      >('vad_pcm16_to_float');
  late final _vad_pcm16_to_float = _vad_pcm16_to_floatPtr
      .asFunction<
        void Function(ffi.Pointer<ffi.Int16>, ffi.Pointer<ffi.Float>, int)
      >();
}

/// Configuration structure for VAD parameters
final class VADConfig extends ffi.Struct {
  /// Threshold for detecting speech start (default: 0.5)
  @ffi.Float()
  external double positive_speech_threshold;

  /// Threshold for detecting speech end (default: 0.35)
  @ffi.Float()
  external double negative_speech_threshold;

  /// Number of frames to prepend before speech start (default: 3 for v6)
  @ffi.Int32()
  external int pre_speech_pad_frames;

  /// Number of silence frames before ending speech (default: 24 for v6)
  @ffi.Int32()
  external int redemption_frames;

  /// Minimum speech frames for valid speech (default: 9 for v6)
  @ffi.Int32()
  external int min_speech_frames;

  /// Audio sample rate in Hz (16000 or 8000)
  @ffi.Int32()
  external int sample_rate;

  /// Number of samples per frame (512 for 16kHz v6, 256 for 8kHz v6)
  @ffi.Int32()
  external int frame_samples;

  /// Number of padding frames after speech end (default: 3 for v6)
  @ffi.Int32()
  external int end_speech_pad_frames;

  /// Enable debug logging (0 = false, 1 = true, using int32_t for FFI compatibility)
  @ffi.Int32()
  external int is_debug;
}

/// Event types emitted by VAD
enum VADEventType {
  VAD_EVENT_INITIALIZED(0),
  VAD_EVENT_SPEECH_START(1),
  VAD_EVENT_SPEECH_END(2),
  VAD_EVENT_FRAME_PROCESSED(3),
  VAD_EVENT_REAL_SPEECH_START(4),
  VAD_EVENT_MISFIRE(5),
  VAD_EVENT_ERROR(6),
  VAD_EVENT_STOPPED(7);

  final int value;
  const VADEventType(this.value);

  static VADEventType fromValue(int value) => switch (value) {
    0 => VAD_EVENT_INITIALIZED,
    1 => VAD_EVENT_SPEECH_START,
    2 => VAD_EVENT_SPEECH_END,
    3 => VAD_EVENT_FRAME_PROCESSED,
    4 => VAD_EVENT_REAL_SPEECH_START,
    5 => VAD_EVENT_MISFIRE,
    6 => VAD_EVENT_ERROR,
    7 => VAD_EVENT_STOPPED,
    _ => throw ArgumentError('Unknown value for VADEventType: $value'),
  };
}

/// VAD Event structure.
///
/// Flat layout — this must match the structs actually emitted by the native
/// implementations (`VADEventCStruct` in ios/macos VadPlusFFI.swift and
/// `VADEventC` in android vad_plus_jni.cpp) and the generated Dart bindings.
/// Only the fields relevant to the current `type` are populated; the rest
/// are zero/NULL.
final class VADEvent extends ffi.Struct {
  /// One of the VADEventType values
  @ffi.Int32()
  external int type;

  /// VAD_EVENT_FRAME_PROCESSED
  /// Speech probability (0.0 - 1.0)
  @ffi.Float()
  external double frame_probability;

  /// Whether current frame is speech (0 = false, 1 = true)
  @ffi.Int32()
  external int frame_is_speech;

  /// Pointer to frame audio data (float32)
  external ffi.Pointer<ffi.Float> frame_data;

  /// Number of samples in frame
  @ffi.Int32()
  external int frame_length;

  /// VAD_EVENT_SPEECH_END
  /// Pointer to PCM16 audio data
  external ffi.Pointer<ffi.Int16> speech_end_audio_data;

  /// Number of samples
  @ffi.Int32()
  external int speech_end_audio_length;

  /// Duration in milliseconds
  @ffi.Int32()
  external int speech_end_duration_ms;

  /// VAD_EVENT_ERROR
  /// Error message
  external ffi.Pointer<ffi.Char> error_message;

  /// Error code
  @ffi.Int32()
  external int error_code;
}

typedef VADEventCallbackFunction =
    ffi.Void Function(
      ffi.Pointer<VADEvent> event,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef DartVADEventCallbackFunction =
    void Function(ffi.Pointer<VADEvent> event, ffi.Pointer<ffi.Void> user_data);

/// Callback function type for VAD events
/// Note: Event is passed by pointer for C/Swift FFI compatibility
typedef VADEventCallback =
    ffi.Pointer<ffi.NativeFunction<VADEventCallbackFunction>>;

final class VADHandle extends ffi.Opaque {}
